# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindowxYcRLO.ui'
##
## Created by: Qt User Interface Compiler version 5.15.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *

from PySide6.QtQuickWidgets import QQuickWidget



class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        if not mainWindow.objectName():
            mainWindow.setObjectName(u"mainWindow")
        mainWindow.resize(1461, 913)
        self.actionQuit = QAction(mainWindow)
        self.actionQuit.setObjectName(u"actionQuit")
        self.actionRecording_Path = QAction(mainWindow)
        self.actionRecording_Path.setObjectName(u"actionRecording_Path")
        self.actionSet_Password = QAction(mainWindow)
        self.actionSet_Password.setObjectName(u"actionSet_Password")
        self.actionNTRIP_Configuration = QAction(mainWindow)
        self.actionNTRIP_Configuration.setObjectName(u"actionNTRIP_Configuration")
        self.actionAbout = QAction(mainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.centralwidget = QWidget(mainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayoutWidget = QWidget(self.centralwidget)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(0, 0, 1461, 891))
        self.dashboard = QGridLayout(self.gridLayoutWidget)
        self.dashboard.setObjectName(u"dashboard")
        self.dashboard.setHorizontalSpacing(14)
        self.dashboard.setVerticalSpacing(12)
        self.dashboard.setContentsMargins(6, 0, 0, 0)
        self.scrollArea = QScrollArea(self.gridLayoutWidget)
        self.scrollArea.setObjectName(u"scrollArea")
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMaximumSize(QSize(16777215, 205))
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 1452, 203))
        self.outputScreen = QTextBrowser(self.scrollAreaWidgetContents)
        self.outputScreen.setObjectName(u"outputScreen")
        self.outputScreen.setGeometry(QRect(0, -10, 1451, 201))
        self.outputScreen.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.dashboard.addWidget(self.scrollArea, 1, 0, 1, 2)

        self.layout_display = QVBoxLayout()
        self.layout_display.setObjectName(u"layout_display")
        self.stackedDisplay = QStackedWidget(self.gridLayoutWidget)
        self.stackedDisplay.setObjectName(u"stackedDisplay")
        self.Values = QWidget()
        self.Values.setObjectName(u"Values")
        self.next_values = QPushButton(self.Values)
        self.next_values.setObjectName(u"next_values")
        self.next_values.setGeometry(QRect(1150, 10, 89, 25))
        self.verticalLayoutWidget_4 = QWidget(self.Values)
        self.verticalLayoutWidget_4.setObjectName(u"verticalLayoutWidget_4")
        self.verticalLayoutWidget_4.setGeometry(QRect(-1, 40, 1241, 631))
        self.layout_values = QVBoxLayout(self.verticalLayoutWidget_4)
        self.layout_values.setObjectName(u"layout_values")
        self.layout_values.setContentsMargins(0, 0, 0, 0)
        self.gridLayout = QGridLayout()
        self.gridLayout.setObjectName(u"gridLayout")
        self.gps = QGroupBox(self.verticalLayoutWidget_4)
        self.gps.setObjectName(u"gps")
        self.longitude = QPlainTextEdit(self.gps)
        self.longitude.setObjectName(u"longitude")
        self.longitude.setGeometry(QRect(90, 60, 161, 21))
#if QT_CONFIG(tooltip)
        self.longitude.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.longitude.setInputMethodHints(Qt.ImhNone)
        self.longitude.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.longitude.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.longitude.setLineWrapMode(QPlainTextEdit.NoWrap)
        self.longitude.setReadOnly(True)
        self.labelLatitude = QLabel(self.gps)
        self.labelLatitude.setObjectName(u"labelLatitude")
        self.labelLatitude.setGeometry(QRect(10, 30, 67, 17))
        self.labelLongitude = QLabel(self.gps)
        self.labelLongitude.setObjectName(u"labelLongitude")
        self.labelLongitude.setGeometry(QRect(10, 60, 81, 17))
        self.latitude = QPlainTextEdit(self.gps)
        self.latitude.setObjectName(u"latitude")
        self.latitude.setGeometry(QRect(90, 30, 161, 21))
#if QT_CONFIG(tooltip)
        self.latitude.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.latitude.setInputMethodHints(Qt.ImhNone)
        self.latitude.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.latitude.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.latitude.setLineWrapMode(QPlainTextEdit.NoWrap)
        self.latitude.setReadOnly(True)
        self.altitude = QPlainTextEdit(self.gps)
        self.altitude.setObjectName(u"altitude")
        self.altitude.setGeometry(QRect(90, 90, 161, 21))
#if QT_CONFIG(tooltip)
        self.altitude.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.altitude.setInputMethodHints(Qt.ImhNone)
        self.altitude.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.altitude.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.altitude.setLineWrapMode(QPlainTextEdit.NoWrap)
        self.altitude.setReadOnly(True)
        self.labelAltitude = QLabel(self.gps)
        self.labelAltitude.setObjectName(u"labelAltitude")
        self.labelAltitude.setGeometry(QRect(10, 90, 67, 17))
        self.labelHeading = QLabel(self.gps)
        self.labelHeading.setObjectName(u"labelHeading")
        self.labelHeading.setGeometry(QRect(10, 120, 67, 17))
        self.heading = QPlainTextEdit(self.gps)
        self.heading.setObjectName(u"heading")
        self.heading.setGeometry(QRect(90, 120, 161, 21))
#if QT_CONFIG(tooltip)
        self.heading.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.heading.setInputMethodHints(Qt.ImhNone)
        self.heading.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.heading.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.heading.setLineWrapMode(QPlainTextEdit.NoWrap)
        self.heading.setReadOnly(True)
        self.labelFix = QLabel(self.gps)
        self.labelFix.setObjectName(u"labelFix")
        self.labelFix.setGeometry(QRect(10, 150, 67, 17))
        self.fix = QPlainTextEdit(self.gps)
        self.fix.setObjectName(u"fix")
        self.fix.setGeometry(QRect(90, 150, 161, 21))
#if QT_CONFIG(tooltip)
        self.fix.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.fix.setInputMethodHints(Qt.ImhNone)
        self.fix.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.fix.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.fix.setLineWrapMode(QPlainTextEdit.NoWrap)
        self.fix.setReadOnly(True)

        self.gridLayout.addWidget(self.gps, 0, 1, 1, 1)

        self.timeGPS = QGroupBox(self.verticalLayoutWidget_4)
        self.timeGPS.setObjectName(u"timeGPS")
        self.labelSystemGPS = QLabel(self.timeGPS)
        self.labelSystemGPS.setObjectName(u"labelSystemGPS")
        self.labelSystemGPS.setGeometry(QRect(10, 30, 67, 17))
        self.labelGPSTime = QLabel(self.timeGPS)
        self.labelGPSTime.setObjectName(u"labelGPSTime")
        self.labelGPSTime.setGeometry(QRect(10, 60, 67, 17))
        self.systemTimeGPS = QPlainTextEdit(self.timeGPS)
        self.systemTimeGPS.setObjectName(u"systemTimeGPS")
        self.systemTimeGPS.setGeometry(QRect(70, 30, 221, 21))
#if QT_CONFIG(tooltip)
        self.systemTimeGPS.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.systemTimeGPS.setInputMethodHints(Qt.ImhNone)
        self.systemTimeGPS.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.systemTimeGPS.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.systemTimeGPS.setLineWrapMode(QPlainTextEdit.NoWrap)
        self.systemTimeGPS.setReadOnly(True)
        self.GPSTime = QPlainTextEdit(self.timeGPS)
        self.GPSTime.setObjectName(u"GPSTime")
        self.GPSTime.setGeometry(QRect(70, 60, 221, 21))
        sizePolicy1 = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.GPSTime.sizePolicy().hasHeightForWidth())
        self.GPSTime.setSizePolicy(sizePolicy1)
#if QT_CONFIG(tooltip)
        self.GPSTime.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.GPSTime.setInputMethodHints(Qt.ImhNone)
        self.GPSTime.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.GPSTime.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.GPSTime.setLineWrapMode(QPlainTextEdit.NoWrap)
        self.GPSTime.setReadOnly(True)

        self.gridLayout.addWidget(self.timeGPS, 0, 0, 1, 1)

        self.ntrip = QGroupBox(self.verticalLayoutWidget_4)
        self.ntrip.setObjectName(u"ntrip")
        self.diffAge = QPlainTextEdit(self.ntrip)
        self.diffAge.setObjectName(u"diffAge")
        self.diffAge.setGeometry(QRect(90, 30, 161, 21))
#if QT_CONFIG(tooltip)
        self.diffAge.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.diffAge.setInputMethodHints(Qt.ImhNone)
        self.diffAge.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.diffAge.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.diffAge.setLineWrapMode(QPlainTextEdit.NoWrap)
        self.diffAge.setReadOnly(True)
        self.labelDiffAge = QLabel(self.ntrip)
        self.labelDiffAge.setObjectName(u"labelDiffAge")
        self.labelDiffAge.setGeometry(QRect(10, 30, 81, 17))
        self.diffStation = QPlainTextEdit(self.ntrip)
        self.diffStation.setObjectName(u"diffStation")
        self.diffStation.setGeometry(QRect(90, 60, 161, 21))
#if QT_CONFIG(tooltip)
        self.diffStation.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.diffStation.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.diffStation.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.diffStation.setLineWrapMode(QPlainTextEdit.NoWrap)
        self.diffStation.setReadOnly(True)
        self.labelDiffStation = QLabel(self.ntrip)
        self.labelDiffStation.setObjectName(u"labelDiffStation")
        self.labelDiffStation.setGeometry(QRect(10, 60, 81, 17))

        self.gridLayout.addWidget(self.ntrip, 2, 1, 1, 1)

        self.status = QGroupBox(self.verticalLayoutWidget_4)
        self.status.setObjectName(u"status")
        self.labelGPSFix = QLabel(self.status)
        self.labelGPSFix.setObjectName(u"labelGPSFix")
        self.labelGPSFix.setGeometry(QRect(10, 120, 67, 17))
        self.hAccu = QPlainTextEdit(self.status)
        self.hAccu.setObjectName(u"hAccu")
        self.hAccu.setGeometry(QRect(90, 30, 161, 21))
#if QT_CONFIG(tooltip)
        self.hAccu.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.hAccu.setInputMethodHints(Qt.ImhNone)
        self.hAccu.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.hAccu.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.hAccu.setLineWrapMode(QPlainTextEdit.NoWrap)
        self.hAccu.setReadOnly(True)
        self.labelhAccu = QLabel(self.status)
        self.labelhAccu.setObjectName(u"labelhAccu")
        self.labelhAccu.setGeometry(QRect(10, 30, 67, 17))
        self.GPSFix = QPlainTextEdit(self.status)
        self.GPSFix.setObjectName(u"GPSFix")
        self.GPSFix.setGeometry(QRect(90, 120, 161, 21))
#if QT_CONFIG(tooltip)
        self.GPSFix.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.GPSFix.setInputMethodHints(Qt.ImhNone)
        self.GPSFix.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.GPSFix.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.GPSFix.setLineWrapMode(QPlainTextEdit.NoWrap)
        self.GPSFix.setReadOnly(True)
        self.vAccu = QPlainTextEdit(self.status)
        self.vAccu.setObjectName(u"vAccu")
        self.vAccu.setGeometry(QRect(90, 60, 161, 21))
#if QT_CONFIG(tooltip)
        self.vAccu.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.vAccu.setInputMethodHints(Qt.ImhNone)
        self.vAccu.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.vAccu.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.vAccu.setLineWrapMode(QPlainTextEdit.NoWrap)
        self.vAccu.setReadOnly(True)
        self.labelvAccu = QLabel(self.status)
        self.labelvAccu.setObjectName(u"labelvAccu")
        self.labelvAccu.setGeometry(QRect(10, 60, 81, 17))
        self.labelacc3D = QLabel(self.status)
        self.labelacc3D.setObjectName(u"labelacc3D")
        self.labelacc3D.setGeometry(QRect(10, 90, 67, 17))
        self.acc3D = QPlainTextEdit(self.status)
        self.acc3D.setObjectName(u"acc3D")
        self.acc3D.setGeometry(QRect(90, 90, 161, 21))
#if QT_CONFIG(tooltip)
        self.acc3D.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.acc3D.setInputMethodHints(Qt.ImhNone)
        self.acc3D.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.acc3D.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.acc3D.setLineWrapMode(QPlainTextEdit.NoWrap)
        self.acc3D.setReadOnly(True)
        self.VDOP = QPlainTextEdit(self.status)
        self.VDOP.setObjectName(u"VDOP")
        self.VDOP.setGeometry(QRect(90, 210, 161, 21))
#if QT_CONFIG(tooltip)
        self.VDOP.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.VDOP.setInputMethodHints(Qt.ImhNone)
        self.VDOP.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.VDOP.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.VDOP.setLineWrapMode(QPlainTextEdit.NoWrap)
        self.VDOP.setReadOnly(True)
        self.PDOP = QPlainTextEdit(self.status)
        self.PDOP.setObjectName(u"PDOP")
        self.PDOP.setGeometry(QRect(90, 240, 161, 21))
#if QT_CONFIG(tooltip)
        self.PDOP.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.PDOP.setInputMethodHints(Qt.ImhNone)
        self.PDOP.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.PDOP.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.PDOP.setLineWrapMode(QPlainTextEdit.NoWrap)
        self.PDOP.setReadOnly(True)
        self.numSat = QPlainTextEdit(self.status)
        self.numSat.setObjectName(u"numSat")
        self.numSat.setGeometry(QRect(90, 150, 161, 21))
#if QT_CONFIG(tooltip)
        self.numSat.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.numSat.setInputMethodHints(Qt.ImhNone)
        self.numSat.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.numSat.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.numSat.setLineWrapMode(QPlainTextEdit.NoWrap)
        self.numSat.setReadOnly(True)
        self.labelPDOP = QLabel(self.status)
        self.labelPDOP.setObjectName(u"labelPDOP")
        self.labelPDOP.setGeometry(QRect(10, 240, 67, 17))
        self.labelHDOP = QLabel(self.status)
        self.labelHDOP.setObjectName(u"labelHDOP")
        self.labelHDOP.setGeometry(QRect(10, 180, 81, 17))
        self.labelVDOP = QLabel(self.status)
        self.labelVDOP.setObjectName(u"labelVDOP")
        self.labelVDOP.setGeometry(QRect(10, 210, 67, 17))
        self.labelnumSat = QLabel(self.status)
        self.labelnumSat.setObjectName(u"labelnumSat")
        self.labelnumSat.setGeometry(QRect(10, 150, 67, 17))
        self.HDOP = QPlainTextEdit(self.status)
        self.HDOP.setObjectName(u"HDOP")
        self.HDOP.setGeometry(QRect(90, 180, 161, 21))
#if QT_CONFIG(tooltip)
        self.HDOP.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.HDOP.setInputMethodHints(Qt.ImhNone)
        self.HDOP.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.HDOP.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.HDOP.setLineWrapMode(QPlainTextEdit.NoWrap)
        self.HDOP.setReadOnly(True)
        self.labelFusionMode = QLabel(self.status)
        self.labelFusionMode.setObjectName(u"labelFusionMode")
        self.labelFusionMode.setGeometry(QRect(10, 270, 67, 17))
        self.fusionMode = QPlainTextEdit(self.status)
        self.fusionMode.setObjectName(u"fusionMode")
        self.fusionMode.setGeometry(QRect(90, 270, 161, 21))
#if QT_CONFIG(tooltip)
        self.fusionMode.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.fusionMode.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.fusionMode.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.fusionMode.setLineWrapMode(QPlainTextEdit.NoWrap)
        self.fusionMode.setReadOnly(True)

        self.gridLayout.addWidget(self.status, 1, 0, 2, 1)

        self.calibration = QGroupBox(self.verticalLayoutWidget_4)
        self.calibration.setObjectName(u"calibration")
        self.calibration.setMinimumSize(QSize(0, 214))
        self.calibGyroZ = QPlainTextEdit(self.calibration)
        self.calibGyroZ.setObjectName(u"calibGyroZ")
        self.calibGyroZ.setGeometry(QRect(90, 90, 161, 21))
#if QT_CONFIG(tooltip)
        self.calibGyroZ.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.calibGyroZ.setInputMethodHints(Qt.ImhNone)
        self.calibGyroZ.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.calibGyroZ.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.calibGyroZ.setLineWrapMode(QPlainTextEdit.NoWrap)
        self.calibGyroZ.setReadOnly(True)
        self.calibAccX = QPlainTextEdit(self.calibration)
        self.calibAccX.setObjectName(u"calibAccX")
        self.calibAccX.setGeometry(QRect(90, 120, 161, 21))
#if QT_CONFIG(tooltip)
        self.calibAccX.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.calibAccX.setInputMethodHints(Qt.ImhNone)
        self.calibAccX.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.calibAccX.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.calibAccX.setLineWrapMode(QPlainTextEdit.NoWrap)
        self.calibAccX.setReadOnly(True)
        self.calibGyroX = QPlainTextEdit(self.calibration)
        self.calibGyroX.setObjectName(u"calibGyroX")
        self.calibGyroX.setGeometry(QRect(90, 30, 161, 21))
#if QT_CONFIG(tooltip)
        self.calibGyroX.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.calibGyroX.setInputMethodHints(Qt.ImhNone)
        self.calibGyroX.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.calibGyroX.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.calibGyroX.setLineWrapMode(QPlainTextEdit.NoWrap)
        self.calibGyroX.setReadOnly(True)
        self.labelAccX_1 = QLabel(self.calibration)
        self.labelAccX_1.setObjectName(u"labelAccX_1")
        self.labelAccX_1.setGeometry(QRect(10, 120, 67, 17))
        self.labelGyroY_1 = QLabel(self.calibration)
        self.labelGyroY_1.setObjectName(u"labelGyroY_1")
        self.labelGyroY_1.setGeometry(QRect(10, 60, 81, 17))
        self.labelGyroZ_1 = QLabel(self.calibration)
        self.labelGyroZ_1.setObjectName(u"labelGyroZ_1")
        self.labelGyroZ_1.setGeometry(QRect(10, 90, 67, 17))
        self.labelGyroX_1 = QLabel(self.calibration)
        self.labelGyroX_1.setObjectName(u"labelGyroX_1")
        self.labelGyroX_1.setGeometry(QRect(10, 30, 67, 17))
        self.labelAccZ_1 = QLabel(self.calibration)
        self.labelAccZ_1.setObjectName(u"labelAccZ_1")
        self.labelAccZ_1.setGeometry(QRect(10, 180, 81, 17))
        self.calibAccZ = QPlainTextEdit(self.calibration)
        self.calibAccZ.setObjectName(u"calibAccZ")
        self.calibAccZ.setGeometry(QRect(90, 180, 161, 21))
#if QT_CONFIG(tooltip)
        self.calibAccZ.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.calibAccZ.setInputMethodHints(Qt.ImhNone)
        self.calibAccZ.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.calibAccZ.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.calibAccZ.setLineWrapMode(QPlainTextEdit.NoWrap)
        self.calibAccZ.setReadOnly(True)
        self.labelAccY_1 = QLabel(self.calibration)
        self.labelAccY_1.setObjectName(u"labelAccY_1")
        self.labelAccY_1.setGeometry(QRect(10, 150, 67, 17))
        self.calibGyroY = QPlainTextEdit(self.calibration)
        self.calibGyroY.setObjectName(u"calibGyroY")
        self.calibGyroY.setGeometry(QRect(90, 60, 161, 21))
#if QT_CONFIG(tooltip)
        self.calibGyroY.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.calibGyroY.setInputMethodHints(Qt.ImhNone)
        self.calibGyroY.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.calibGyroY.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.calibGyroY.setLineWrapMode(QPlainTextEdit.NoWrap)
        self.calibGyroY.setReadOnly(True)
        self.calibAccY = QPlainTextEdit(self.calibration)
        self.calibAccY.setObjectName(u"calibAccY")
        self.calibAccY.setGeometry(QRect(90, 150, 161, 21))
#if QT_CONFIG(tooltip)
        self.calibAccY.setToolTip(u"")
#endif // QT_CONFIG(tooltip)
        self.calibAccY.setInputMethodHints(Qt.ImhNone)
        self.calibAccY.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.calibAccY.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.calibAccY.setLineWrapMode(QPlainTextEdit.NoWrap)
        self.calibAccY.setReadOnly(True)

        self.gridLayout.addWidget(self.calibration, 1, 1, 1, 1)

        self.map = QWidget(self.verticalLayoutWidget_4)
        self.map.setObjectName(u"map")
        self.mapwidget = QQuickWidget(self.map)
        self.mapwidget.setObjectName(u"mapwidget")
        self.mapwidget.setGeometry(QRect(0, 0, 611, 631))
        self.mapwidget.setResizeMode(QQuickWidget.SizeRootObjectToView)

        self.gridLayout.addWidget(self.map, 0, 2, 3, 2)


        self.layout_values.addLayout(self.gridLayout)

        self.Label_values = QLabel(self.Values)
        self.Label_values.setObjectName(u"Label_values")
        self.Label_values.setGeometry(QRect(10, 0, 931, 36))
        sizePolicy2 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Maximum)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.Label_values.sizePolicy().hasHeightForWidth())
        self.Label_values.setSizePolicy(sizePolicy2)
        self.Label_values.setMaximumSize(QSize(1209, 16777215))
        font = QFont()
        font.setPointSize(24)
        self.Label_values.setFont(font)
        self.serial_values = QGroupBox(self.Values)
        self.serial_values.setObjectName(u"serial_values")
        self.serial_values.setGeometry(QRect(1250, 10, 192, 661))
        self.serial_values.setMinimumSize(QSize(192, 0))
        self.gpsSerial = QComboBox(self.serial_values)
        self.gpsSerial.setObjectName(u"gpsSerial")
        self.gpsSerial.setGeometry(QRect(70, 30, 101, 22))
        self.serialConnectionButton = QPushButton(self.serial_values)
        self.serialConnectionButton.setObjectName(u"serialConnectionButton")
        self.serialConnectionButton.setGeometry(QRect(10, 170, 80, 22))
        self.serialTerminationButton = QPushButton(self.serial_values)
        self.serialTerminationButton.setObjectName(u"serialTerminationButton")
        self.serialTerminationButton.setEnabled(False)
        self.serialTerminationButton.setGeometry(QRect(100, 170, 80, 22))
        self.baudLabel = QLabel(self.serial_values)
        self.baudLabel.setObjectName(u"baudLabel")
        self.baudLabel.setGeometry(QRect(10, 60, 81, 20))
        self.baudGPS = QComboBox(self.serial_values)
        self.baudGPS.addItem("")
        self.baudGPS.addItem("")
        self.baudGPS.addItem("")
        self.baudGPS.addItem("")
        self.baudGPS.addItem("")
        self.baudGPS.addItem("")
        self.baudGPS.addItem("")
        self.baudGPS.addItem("")
        self.baudGPS.addItem("")
        self.baudGPS.addItem("")
        self.baudGPS.addItem("")
        self.baudGPS.addItem("")
        self.baudGPS.addItem("")
        self.baudGPS.addItem("")
        self.baudGPS.setObjectName(u"baudGPS")
        self.baudGPS.setEnabled(True)
        self.baudGPS.setGeometry(QRect(70, 60, 101, 25))
        self.baudGPS.setEditable(False)
        self.baudGPS.setMinimumContentsLength(0)
        self.serialLabel = QLabel(self.serial_values)
        self.serialLabel.setObjectName(u"serialLabel")
        self.serialLabel.setGeometry(QRect(10, 30, 81, 20))
        self.recordingFolderbtn = QPushButton(self.serial_values)
        self.recordingFolderbtn.setObjectName(u"recordingFolderbtn")
        self.recordingFolderbtn.setGeometry(QRect(10, 200, 171, 25))
        self.ntripConnection = QCheckBox(self.serial_values)
        self.ntripConnection.setObjectName(u"ntripConnection")
        self.ntripConnection.setGeometry(QRect(10, 110, 151, 23))
        self.ntripConnection.setChecked(True)
        self.saveButton = QCheckBox(self.serial_values)
        self.saveButton.setObjectName(u"saveButton")
        self.saveButton.setGeometry(QRect(10, 130, 92, 23))
        self.saveButton.setChecked(True)
        self.saveButton.setTristate(False)
        self.btnGPSStatus = QPushButton(self.serial_values)
        self.btnGPSStatus.setObjectName(u"btnGPSStatus")
        self.btnGPSStatus.setGeometry(QRect(10, 230, 171, 25))
        self.prev_values = QPushButton(self.Values)
        self.prev_values.setObjectName(u"prev_values")
        self.prev_values.setGeometry(QRect(1050, 10, 89, 25))
        self.stackedDisplay.addWidget(self.Values)
        self.Depthai = QWidget()
        self.Depthai.setObjectName(u"Depthai")
        self.verticalLayoutWidget_3 = QWidget(self.Depthai)
        self.verticalLayoutWidget_3.setObjectName(u"verticalLayoutWidget_3")
        self.verticalLayoutWidget_3.setGeometry(QRect(-1, 40, 1241, 631))
        self.layout_video_depthai = QVBoxLayout(self.verticalLayoutWidget_3)
        self.layout_video_depthai.setObjectName(u"layout_video_depthai")
        self.layout_video_depthai.setContentsMargins(0, 0, 0, 0)
        self.videoDepthai = QLabel(self.verticalLayoutWidget_3)
        self.videoDepthai.setObjectName(u"videoDepthai")
        self.videoDepthai.setAlignment(Qt.AlignCenter)

        self.layout_video_depthai.addWidget(self.videoDepthai)

        self.next_depthai = QPushButton(self.Depthai)
        self.next_depthai.setObjectName(u"next_depthai")
        self.next_depthai.setGeometry(QRect(1150, 10, 89, 25))
        self.Label_depthai = QLabel(self.Depthai)
        self.Label_depthai.setObjectName(u"Label_depthai")
        self.Label_depthai.setGeometry(QRect(10, 0, 871, 36))
        sizePolicy2.setHeightForWidth(self.Label_depthai.sizePolicy().hasHeightForWidth())
        self.Label_depthai.setSizePolicy(sizePolicy2)
        self.Label_depthai.setMaximumSize(QSize(1209, 16777215))
        self.Label_depthai.setFont(font)
        self.serial_depthai = QGroupBox(self.Depthai)
        self.serial_depthai.setObjectName(u"serial_depthai")
        self.serial_depthai.setGeometry(QRect(1250, 10, 192, 661))
        self.serial_depthai.setMinimumSize(QSize(192, 0))
        self.resolutionDepthai = QComboBox(self.serial_depthai)
        self.resolutionDepthai.addItem("")
        self.resolutionDepthai.addItem("")
        self.resolutionDepthai.addItem("")
        self.resolutionDepthai.addItem("")
        self.resolutionDepthai.setObjectName(u"resolutionDepthai")
        self.resolutionDepthai.setGeometry(QRect(90, 30, 81, 22))
        self.startrecDepthai = QPushButton(self.serial_depthai)
        self.startrecDepthai.setObjectName(u"startrecDepthai")
        self.startrecDepthai.setGeometry(QRect(10, 140, 80, 22))
        self.stoprecDepthai = QPushButton(self.serial_depthai)
        self.stoprecDepthai.setObjectName(u"stoprecDepthai")
        self.stoprecDepthai.setEnabled(False)
        self.stoprecDepthai.setGeometry(QRect(100, 140, 80, 22))
        self.fpsDepthaiLabel = QLabel(self.serial_depthai)
        self.fpsDepthaiLabel.setObjectName(u"fpsDepthaiLabel")
        self.fpsDepthaiLabel.setGeometry(QRect(10, 60, 81, 20))
        self.fpsDepthai = QComboBox(self.serial_depthai)
        self.fpsDepthai.addItem("")
        self.fpsDepthai.addItem("")
        self.fpsDepthai.addItem("")
        self.fpsDepthai.addItem("")
        self.fpsDepthai.addItem("")
        self.fpsDepthai.addItem("")
        self.fpsDepthai.addItem("")
        self.fpsDepthai.addItem("")
        self.fpsDepthai.addItem("")
        self.fpsDepthai.addItem("")
        self.fpsDepthai.addItem("")
        self.fpsDepthai.addItem("")
        self.fpsDepthai.setObjectName(u"fpsDepthai")
        self.fpsDepthai.setEnabled(True)
        self.fpsDepthai.setGeometry(QRect(70, 60, 101, 25))
        self.fpsDepthai.setEditable(False)
        self.fpsDepthai.setMinimumContentsLength(0)
        self.resolutionDepthaiLabel = QLabel(self.serial_depthai)
        self.resolutionDepthaiLabel.setObjectName(u"resolutionDepthaiLabel")
        self.resolutionDepthaiLabel.setGeometry(QRect(10, 30, 81, 20))
        self.initializeDepthai = QPushButton(self.serial_depthai)
        self.initializeDepthai.setObjectName(u"initializeDepthai")
        self.initializeDepthai.setGeometry(QRect(10, 110, 171, 25))
        self.exposureDepthaiLabel = QLabel(self.serial_depthai)
        self.exposureDepthaiLabel.setObjectName(u"exposureDepthaiLabel")
        self.exposureDepthaiLabel.setGeometry(QRect(10, 190, 81, 20))
        self.exposureDepthaiAdd = QPushButton(self.serial_depthai)
        self.exposureDepthaiAdd.setObjectName(u"exposureDepthaiAdd")
        self.exposureDepthaiAdd.setGeometry(QRect(110, 190, 21, 22))
        self.exposureDepthaiSub = QPushButton(self.serial_depthai)
        self.exposureDepthaiSub.setObjectName(u"exposureDepthaiSub")
        self.exposureDepthaiSub.setGeometry(QRect(140, 190, 21, 22))
        self.ISODepthaiLabel = QLabel(self.serial_depthai)
        self.ISODepthaiLabel.setObjectName(u"ISODepthaiLabel")
        self.ISODepthaiLabel.setGeometry(QRect(10, 220, 81, 20))
        self.ISODepthaiAdd = QPushButton(self.serial_depthai)
        self.ISODepthaiAdd.setObjectName(u"ISODepthaiAdd")
        self.ISODepthaiAdd.setGeometry(QRect(110, 220, 21, 22))
        self.ISODepthaiSub = QPushButton(self.serial_depthai)
        self.ISODepthaiSub.setObjectName(u"ISODepthaiSub")
        self.ISODepthaiSub.setGeometry(QRect(140, 220, 21, 22))
        self.focusDepthaiLabel = QLabel(self.serial_depthai)
        self.focusDepthaiLabel.setObjectName(u"focusDepthaiLabel")
        self.focusDepthaiLabel.setGeometry(QRect(10, 250, 81, 20))
        self.focusDepthaiAdd = QPushButton(self.serial_depthai)
        self.focusDepthaiAdd.setObjectName(u"focusDepthaiAdd")
        self.focusDepthaiAdd.setGeometry(QRect(110, 250, 21, 22))
        self.focusDepthaiSub = QPushButton(self.serial_depthai)
        self.focusDepthaiSub.setObjectName(u"focusDepthaiSub")
        self.focusDepthaiSub.setGeometry(QRect(140, 250, 21, 22))
        self.brightnessDeptthaiLabel = QLabel(self.serial_depthai)
        self.brightnessDeptthaiLabel.setObjectName(u"brightnessDeptthaiLabel")
        self.brightnessDeptthaiLabel.setGeometry(QRect(10, 280, 81, 20))
        self.brightnessDepthaiAdd = QPushButton(self.serial_depthai)
        self.brightnessDepthaiAdd.setObjectName(u"brightnessDepthaiAdd")
        self.brightnessDepthaiAdd.setGeometry(QRect(110, 280, 21, 22))
        self.brightnessDepthaiSub = QPushButton(self.serial_depthai)
        self.brightnessDepthaiSub.setObjectName(u"brightnessDepthaiSub")
        self.brightnessDepthaiSub.setGeometry(QRect(140, 280, 21, 22))
        self.contrastDepthaiSub = QPushButton(self.serial_depthai)
        self.contrastDepthaiSub.setObjectName(u"contrastDepthaiSub")
        self.contrastDepthaiSub.setGeometry(QRect(140, 310, 21, 22))
        self.contrastDepthaiAdd = QPushButton(self.serial_depthai)
        self.contrastDepthaiAdd.setObjectName(u"contrastDepthaiAdd")
        self.contrastDepthaiAdd.setGeometry(QRect(110, 310, 21, 22))
        self.contrastDepthaiLabel = QLabel(self.serial_depthai)
        self.contrastDepthaiLabel.setObjectName(u"contrastDepthaiLabel")
        self.contrastDepthaiLabel.setGeometry(QRect(10, 310, 81, 20))
        self.saturationDepthaiSub = QPushButton(self.serial_depthai)
        self.saturationDepthaiSub.setObjectName(u"saturationDepthaiSub")
        self.saturationDepthaiSub.setGeometry(QRect(140, 340, 21, 22))
        self.saturationDepthaiAdd = QPushButton(self.serial_depthai)
        self.saturationDepthaiAdd.setObjectName(u"saturationDepthaiAdd")
        self.saturationDepthaiAdd.setGeometry(QRect(110, 340, 21, 22))
        self.saturationDepthaiLabel = QLabel(self.serial_depthai)
        self.saturationDepthaiLabel.setObjectName(u"saturationDepthaiLabel")
        self.saturationDepthaiLabel.setGeometry(QRect(10, 340, 81, 20))
        self.sharpnessDepthaiLabel = QLabel(self.serial_depthai)
        self.sharpnessDepthaiLabel.setObjectName(u"sharpnessDepthaiLabel")
        self.sharpnessDepthaiLabel.setGeometry(QRect(10, 370, 81, 20))
        self.sharpnessDepthaiAdd = QPushButton(self.serial_depthai)
        self.sharpnessDepthaiAdd.setObjectName(u"sharpnessDepthaiAdd")
        self.sharpnessDepthaiAdd.setGeometry(QRect(110, 370, 21, 22))
        self.sharpnessDepthaiSub = QPushButton(self.serial_depthai)
        self.sharpnessDepthaiSub.setObjectName(u"sharpnessDepthaiSub")
        self.sharpnessDepthaiSub.setGeometry(QRect(140, 370, 21, 22))
        self.autoexposureDepthai = QPushButton(self.serial_depthai)
        self.autoexposureDepthai.setObjectName(u"autoexposureDepthai")
        self.autoexposureDepthai.setGeometry(QRect(10, 410, 171, 25))
        self.autofocusDepthai = QPushButton(self.serial_depthai)
        self.autofocusDepthai.setObjectName(u"autofocusDepthai")
        self.autofocusDepthai.setGeometry(QRect(10, 440, 171, 25))
        self.autowbDepthai = QPushButton(self.serial_depthai)
        self.autowbDepthai.setObjectName(u"autowbDepthai")
        self.autowbDepthai.setGeometry(QRect(10, 470, 171, 25))
        self.rosDepthaiUp = QPushButton(self.serial_depthai)
        self.rosDepthaiUp.setObjectName(u"rosDepthaiUp")
        self.rosDepthaiUp.setGeometry(QRect(80, 520, 21, 22))
        self.rosDepthaiLeft = QPushButton(self.serial_depthai)
        self.rosDepthaiLeft.setObjectName(u"rosDepthaiLeft")
        self.rosDepthaiLeft.setGeometry(QRect(40, 550, 21, 22))
        self.rosDepthaiDown = QPushButton(self.serial_depthai)
        self.rosDepthaiDown.setObjectName(u"rosDepthaiDown")
        self.rosDepthaiDown.setGeometry(QRect(80, 580, 21, 22))
        self.rosDepthaiRight = QPushButton(self.serial_depthai)
        self.rosDepthaiRight.setObjectName(u"rosDepthaiRight")
        self.rosDepthaiRight.setGeometry(QRect(120, 550, 21, 22))
        self.prev_depthai = QPushButton(self.Depthai)
        self.prev_depthai.setObjectName(u"prev_depthai")
        self.prev_depthai.setGeometry(QRect(1050, 10, 89, 25))
        self.stackedDisplay.addWidget(self.Depthai)
        self.Label_depthai.raise_()
        self.verticalLayoutWidget_3.raise_()
        self.next_depthai.raise_()
        self.serial_depthai.raise_()
        self.prev_depthai.raise_()
        self.Zed = QWidget()
        self.Zed.setObjectName(u"Zed")
        self.next_zed = QPushButton(self.Zed)
        self.next_zed.setObjectName(u"next_zed")
        self.next_zed.setGeometry(QRect(1150, 10, 89, 25))
        self.label_zed = QLabel(self.Zed)
        self.label_zed.setObjectName(u"label_zed")
        self.label_zed.setGeometry(QRect(10, 0, 871, 36))
        sizePolicy2.setHeightForWidth(self.label_zed.sizePolicy().hasHeightForWidth())
        self.label_zed.setSizePolicy(sizePolicy2)
        self.label_zed.setMaximumSize(QSize(1209, 16777215))
        self.label_zed.setFont(font)
        self.serial_zed = QGroupBox(self.Zed)
        self.serial_zed.setObjectName(u"serial_zed")
        self.serial_zed.setGeometry(QRect(1250, 10, 192, 661))
        self.serial_zed.setMinimumSize(QSize(192, 0))
        self.resolutionZed = QComboBox(self.serial_zed)
        self.resolutionZed.addItem("")
        self.resolutionZed.addItem("")
        self.resolutionZed.addItem("")
        self.resolutionZed.setObjectName(u"resolutionZed")
        self.resolutionZed.setGeometry(QRect(90, 30, 81, 22))
        self.startrecZed = QPushButton(self.serial_zed)
        self.startrecZed.setObjectName(u"startrecZed")
        self.startrecZed.setGeometry(QRect(10, 140, 80, 22))
        self.stoprecZed = QPushButton(self.serial_zed)
        self.stoprecZed.setObjectName(u"stoprecZed")
        self.stoprecZed.setEnabled(False)
        self.stoprecZed.setGeometry(QRect(100, 140, 80, 22))
        self.fpsZedLabel = QLabel(self.serial_zed)
        self.fpsZedLabel.setObjectName(u"fpsZedLabel")
        self.fpsZedLabel.setGeometry(QRect(10, 60, 81, 20))
        self.fpsZed = QComboBox(self.serial_zed)
        self.fpsZed.addItem("")
        self.fpsZed.addItem("")
        self.fpsZed.addItem("")
        self.fpsZed.addItem("")
        self.fpsZed.addItem("")
        self.fpsZed.addItem("")
        self.fpsZed.addItem("")
        self.fpsZed.addItem("")
        self.fpsZed.addItem("")
        self.fpsZed.addItem("")
        self.fpsZed.addItem("")
        self.fpsZed.addItem("")
        self.fpsZed.setObjectName(u"fpsZed")
        self.fpsZed.setEnabled(True)
        self.fpsZed.setGeometry(QRect(70, 60, 101, 25))
        self.fpsZed.setEditable(False)
        self.fpsZed.setMinimumContentsLength(0)
        self.resolutionZedLabel = QLabel(self.serial_zed)
        self.resolutionZedLabel.setObjectName(u"resolutionZedLabel")
        self.resolutionZedLabel.setGeometry(QRect(10, 30, 81, 20))
        self.initializeZed = QPushButton(self.serial_zed)
        self.initializeZed.setObjectName(u"initializeZed")
        self.initializeZed.setGeometry(QRect(10, 110, 171, 25))
        self.exposureZedLabel = QLabel(self.serial_zed)
        self.exposureZedLabel.setObjectName(u"exposureZedLabel")
        self.exposureZedLabel.setGeometry(QRect(10, 190, 81, 20))
        self.exposureZedAdd = QPushButton(self.serial_zed)
        self.exposureZedAdd.setObjectName(u"exposureZedAdd")
        self.exposureZedAdd.setGeometry(QRect(110, 190, 21, 22))
        self.exposureZedSub = QPushButton(self.serial_zed)
        self.exposureZedSub.setObjectName(u"exposureZedSub")
        self.exposureZedSub.setGeometry(QRect(140, 190, 21, 22))
        self.gainZedLabel = QLabel(self.serial_zed)
        self.gainZedLabel.setObjectName(u"gainZedLabel")
        self.gainZedLabel.setGeometry(QRect(10, 220, 81, 20))
        self.gainZedAdd = QPushButton(self.serial_zed)
        self.gainZedAdd.setObjectName(u"gainZedAdd")
        self.gainZedAdd.setGeometry(QRect(110, 220, 21, 22))
        self.gainZedSub = QPushButton(self.serial_zed)
        self.gainZedSub.setObjectName(u"gainZedSub")
        self.gainZedSub.setGeometry(QRect(140, 220, 21, 22))
        self.hueZedLabel = QLabel(self.serial_zed)
        self.hueZedLabel.setObjectName(u"hueZedLabel")
        self.hueZedLabel.setGeometry(QRect(10, 250, 81, 20))
        self.hueZedAdd = QPushButton(self.serial_zed)
        self.hueZedAdd.setObjectName(u"hueZedAdd")
        self.hueZedAdd.setGeometry(QRect(110, 250, 21, 22))
        self.hueZedSub = QPushButton(self.serial_zed)
        self.hueZedSub.setObjectName(u"hueZedSub")
        self.hueZedSub.setGeometry(QRect(140, 250, 21, 22))
        self.brightnessZedLabel = QLabel(self.serial_zed)
        self.brightnessZedLabel.setObjectName(u"brightnessZedLabel")
        self.brightnessZedLabel.setGeometry(QRect(10, 280, 81, 20))
        self.brightnessZedAdd = QPushButton(self.serial_zed)
        self.brightnessZedAdd.setObjectName(u"brightnessZedAdd")
        self.brightnessZedAdd.setGeometry(QRect(110, 280, 21, 22))
        self.brightnessZedSub = QPushButton(self.serial_zed)
        self.brightnessZedSub.setObjectName(u"brightnessZedSub")
        self.brightnessZedSub.setGeometry(QRect(140, 280, 21, 22))
        self.contrastZedSub = QPushButton(self.serial_zed)
        self.contrastZedSub.setObjectName(u"contrastZedSub")
        self.contrastZedSub.setGeometry(QRect(140, 310, 21, 22))
        self.contrastZedAdd = QPushButton(self.serial_zed)
        self.contrastZedAdd.setObjectName(u"contrastZedAdd")
        self.contrastZedAdd.setGeometry(QRect(110, 310, 21, 22))
        self.contrastZedLabel = QLabel(self.serial_zed)
        self.contrastZedLabel.setObjectName(u"contrastZedLabel")
        self.contrastZedLabel.setGeometry(QRect(10, 310, 81, 20))
        self.saturationZedSub = QPushButton(self.serial_zed)
        self.saturationZedSub.setObjectName(u"saturationZedSub")
        self.saturationZedSub.setGeometry(QRect(140, 340, 21, 22))
        self.saturationZedAdd = QPushButton(self.serial_zed)
        self.saturationZedAdd.setObjectName(u"saturationZedAdd")
        self.saturationZedAdd.setGeometry(QRect(110, 340, 21, 22))
        self.saturationZedLabel = QLabel(self.serial_zed)
        self.saturationZedLabel.setObjectName(u"saturationZedLabel")
        self.saturationZedLabel.setGeometry(QRect(10, 340, 81, 20))
        self.sharpnessZedLabel = QLabel(self.serial_zed)
        self.sharpnessZedLabel.setObjectName(u"sharpnessZedLabel")
        self.sharpnessZedLabel.setGeometry(QRect(10, 370, 81, 20))
        self.sharpnessZedAdd = QPushButton(self.serial_zed)
        self.sharpnessZedAdd.setObjectName(u"sharpnessZedAdd")
        self.sharpnessZedAdd.setGeometry(QRect(110, 370, 21, 22))
        self.sharpnessZedSub = QPushButton(self.serial_zed)
        self.sharpnessZedSub.setObjectName(u"sharpnessZedSub")
        self.sharpnessZedSub.setGeometry(QRect(140, 370, 21, 22))
        self.autoexposureZed = QPushButton(self.serial_zed)
        self.autoexposureZed.setObjectName(u"autoexposureZed")
        self.autoexposureZed.setGeometry(QRect(10, 410, 171, 25))
        self.rosZedUp = QPushButton(self.serial_zed)
        self.rosZedUp.setObjectName(u"rosZedUp")
        self.rosZedUp.setGeometry(QRect(80, 520, 21, 22))
        self.rosZedLeft = QPushButton(self.serial_zed)
        self.rosZedLeft.setObjectName(u"rosZedLeft")
        self.rosZedLeft.setGeometry(QRect(40, 550, 21, 22))
        self.rosZedDown = QPushButton(self.serial_zed)
        self.rosZedDown.setObjectName(u"rosZedDown")
        self.rosZedDown.setGeometry(QRect(80, 580, 21, 22))
        self.rosZedRight = QPushButton(self.serial_zed)
        self.rosZedRight.setObjectName(u"rosZedRight")
        self.rosZedRight.setGeometry(QRect(120, 550, 21, 22))
        self.autobrightnessZed = QPushButton(self.serial_zed)
        self.autobrightnessZed.setObjectName(u"autobrightnessZed")
        self.autobrightnessZed.setGeometry(QRect(10, 440, 171, 25))
        self.resetZed = QPushButton(self.serial_zed)
        self.resetZed.setObjectName(u"resetZed")
        self.resetZed.setGeometry(QRect(10, 470, 171, 25))
        self.verticalLayoutWidget_7 = QWidget(self.Zed)
        self.verticalLayoutWidget_7.setObjectName(u"verticalLayoutWidget_7")
        self.verticalLayoutWidget_7.setGeometry(QRect(0, 40, 1241, 631))
        self.layout_video_zed = QVBoxLayout(self.verticalLayoutWidget_7)
        self.layout_video_zed.setObjectName(u"layout_video_zed")
        self.layout_video_zed.setContentsMargins(0, 0, 0, 0)
        self.videoZed = QLabel(self.verticalLayoutWidget_7)
        self.videoZed.setObjectName(u"videoZed")
        self.videoZed.setAlignment(Qt.AlignCenter)

        self.layout_video_zed.addWidget(self.videoZed)

        self.prev_zed = QPushButton(self.Zed)
        self.prev_zed.setObjectName(u"prev_zed")
        self.prev_zed.setGeometry(QRect(1050, 10, 89, 25))
        self.stackedDisplay.addWidget(self.Zed)

        self.layout_display.addWidget(self.stackedDisplay)


        self.dashboard.addLayout(self.layout_display, 0, 0, 1, 2)

        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(mainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1461, 20))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuSettings = QMenu(self.menubar)
        self.menuSettings.setObjectName(u"menuSettings")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        mainWindow.setMenuBar(self.menubar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionQuit)
        self.menuSettings.addAction(self.actionRecording_Path)
        self.menuSettings.addAction(self.actionSet_Password)
        self.menuSettings.addAction(self.actionNTRIP_Configuration)
        self.menuHelp.addAction(self.actionAbout)

        self.retranslateUi(mainWindow)

        self.stackedDisplay.setCurrentIndex(0)
        self.baudGPS.setCurrentIndex(11)
        self.resolutionDepthai.setCurrentIndex(3)
        self.fpsDepthai.setCurrentIndex(5)
        self.resolutionZed.setCurrentIndex(1)
        self.fpsZed.setCurrentIndex(11)


        QMetaObject.connectSlotsByName(mainWindow)
    # setupUi

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(QCoreApplication.translate("mainWindow", u"Residential Parking Project", None))
        self.actionQuit.setText(QCoreApplication.translate("mainWindow", u"Quit", None))
        self.actionRecording_Path.setText(QCoreApplication.translate("mainWindow", u"Recording Path", None))
        self.actionSet_Password.setText(QCoreApplication.translate("mainWindow", u"Set Password", None))
        self.actionNTRIP_Configuration.setText(QCoreApplication.translate("mainWindow", u"NTRIP Configuration", None))
        self.actionAbout.setText(QCoreApplication.translate("mainWindow", u"About", None))
        self.next_values.setText(QCoreApplication.translate("mainWindow", u"Next", None))
        self.gps.setTitle(QCoreApplication.translate("mainWindow", u"GPS Data", None))
        self.longitude.setPlaceholderText(QCoreApplication.translate("mainWindow", u"0", None))
        self.labelLatitude.setText(QCoreApplication.translate("mainWindow", u"Latitude", None))
        self.labelLongitude.setText(QCoreApplication.translate("mainWindow", u"Longitude", None))
        self.latitude.setPlaceholderText(QCoreApplication.translate("mainWindow", u"0", None))
        self.altitude.setPlaceholderText(QCoreApplication.translate("mainWindow", u"0", None))
        self.labelAltitude.setText(QCoreApplication.translate("mainWindow", u"Altitude", None))
        self.labelHeading.setText(QCoreApplication.translate("mainWindow", u"Heading", None))
        self.heading.setPlaceholderText(QCoreApplication.translate("mainWindow", u"0", None))
        self.labelFix.setText(QCoreApplication.translate("mainWindow", u"Fix", None))
        self.fix.setPlaceholderText(QCoreApplication.translate("mainWindow", u"0", None))
        self.timeGPS.setTitle(QCoreApplication.translate("mainWindow", u"GPS Time", None))
        self.labelSystemGPS.setText(QCoreApplication.translate("mainWindow", u"Time", None))
        self.labelGPSTime.setText(QCoreApplication.translate("mainWindow", u"GPS", None))
        self.systemTimeGPS.setPlaceholderText(QCoreApplication.translate("mainWindow", u"0", None))
        self.GPSTime.setPlaceholderText(QCoreApplication.translate("mainWindow", u"0", None))
        self.ntrip.setTitle(QCoreApplication.translate("mainWindow", u"NTRIP Status", None))
        self.diffAge.setPlaceholderText(QCoreApplication.translate("mainWindow", u"0", None))
        self.labelDiffAge.setText(QCoreApplication.translate("mainWindow", u"Diff Age", None))
        self.diffStation.setPlaceholderText(QCoreApplication.translate("mainWindow", u"0", None))
        self.labelDiffStation.setText(QCoreApplication.translate("mainWindow", u"Diff Station", None))
        self.status.setTitle(QCoreApplication.translate("mainWindow", u"Status", None))
        self.labelGPSFix.setText(QCoreApplication.translate("mainWindow", u"GPS Fix", None))
        self.hAccu.setPlaceholderText(QCoreApplication.translate("mainWindow", u"0", None))
        self.labelhAccu.setText(QCoreApplication.translate("mainWindow", u"2D HAcc", None))
        self.GPSFix.setPlaceholderText(QCoreApplication.translate("mainWindow", u"0", None))
        self.vAccu.setPlaceholderText(QCoreApplication.translate("mainWindow", u"0", None))
        self.labelvAccu.setText(QCoreApplication.translate("mainWindow", u"2D VAcc", None))
        self.labelacc3D.setText(QCoreApplication.translate("mainWindow", u"3D Acc", None))
        self.acc3D.setPlaceholderText(QCoreApplication.translate("mainWindow", u"0", None))
        self.VDOP.setPlaceholderText(QCoreApplication.translate("mainWindow", u"0", None))
        self.PDOP.setPlaceholderText(QCoreApplication.translate("mainWindow", u"0", None))
        self.numSat.setPlaceholderText(QCoreApplication.translate("mainWindow", u"0", None))
        self.labelPDOP.setText(QCoreApplication.translate("mainWindow", u"PDOP", None))
        self.labelHDOP.setText(QCoreApplication.translate("mainWindow", u"HDOP", None))
        self.labelVDOP.setText(QCoreApplication.translate("mainWindow", u"VDOP", None))
        self.labelnumSat.setText(QCoreApplication.translate("mainWindow", u"Num Sat", None))
        self.HDOP.setPlaceholderText(QCoreApplication.translate("mainWindow", u"0", None))
        self.labelFusionMode.setText(QCoreApplication.translate("mainWindow", u"Fusion", None))
        self.fusionMode.setPlaceholderText(QCoreApplication.translate("mainWindow", u"0", None))
        self.calibration.setTitle(QCoreApplication.translate("mainWindow", u"Calibation Status", None))
        self.calibGyroZ.setPlaceholderText(QCoreApplication.translate("mainWindow", u"0", None))
        self.calibAccX.setPlaceholderText(QCoreApplication.translate("mainWindow", u"0", None))
        self.calibGyroX.setPlaceholderText(QCoreApplication.translate("mainWindow", u"0", None))
        self.labelAccX_1.setText(QCoreApplication.translate("mainWindow", u"acc X", None))
        self.labelGyroY_1.setText(QCoreApplication.translate("mainWindow", u"gyro Y", None))
        self.labelGyroZ_1.setText(QCoreApplication.translate("mainWindow", u"gyro Z", None))
        self.labelGyroX_1.setText(QCoreApplication.translate("mainWindow", u"gyro X", None))
        self.labelAccZ_1.setText(QCoreApplication.translate("mainWindow", u"acc Z", None))
        self.calibAccZ.setPlaceholderText(QCoreApplication.translate("mainWindow", u"0", None))
        self.labelAccY_1.setText(QCoreApplication.translate("mainWindow", u"acc Y", None))
        self.calibGyroY.setPlaceholderText(QCoreApplication.translate("mainWindow", u"0", None))
        self.calibAccY.setPlaceholderText(QCoreApplication.translate("mainWindow", u"0", None))
        self.Label_values.setText(QCoreApplication.translate("mainWindow", u"GPS", None))
        self.serial_values.setTitle(QCoreApplication.translate("mainWindow", u"GPS Connections", None))
        self.serialConnectionButton.setText(QCoreApplication.translate("mainWindow", u"Start", None))
        self.serialTerminationButton.setText(QCoreApplication.translate("mainWindow", u"Stop", None))
        self.baudLabel.setText(QCoreApplication.translate("mainWindow", u"Baud", None))
        self.baudGPS.setItemText(0, QCoreApplication.translate("mainWindow", u"110", None))
        self.baudGPS.setItemText(1, QCoreApplication.translate("mainWindow", u"300", None))
        self.baudGPS.setItemText(2, QCoreApplication.translate("mainWindow", u"600", None))
        self.baudGPS.setItemText(3, QCoreApplication.translate("mainWindow", u"1200", None))
        self.baudGPS.setItemText(4, QCoreApplication.translate("mainWindow", u"2400", None))
        self.baudGPS.setItemText(5, QCoreApplication.translate("mainWindow", u"4800", None))
        self.baudGPS.setItemText(6, QCoreApplication.translate("mainWindow", u"9600", None))
        self.baudGPS.setItemText(7, QCoreApplication.translate("mainWindow", u"14400", None))
        self.baudGPS.setItemText(8, QCoreApplication.translate("mainWindow", u"19200", None))
        self.baudGPS.setItemText(9, QCoreApplication.translate("mainWindow", u"38400", None))
        self.baudGPS.setItemText(10, QCoreApplication.translate("mainWindow", u"57600", None))
        self.baudGPS.setItemText(11, QCoreApplication.translate("mainWindow", u"115200", None))
        self.baudGPS.setItemText(12, QCoreApplication.translate("mainWindow", u"128000", None))
        self.baudGPS.setItemText(13, QCoreApplication.translate("mainWindow", u"256000", None))

        self.serialLabel.setText(QCoreApplication.translate("mainWindow", u"Port", None))
        self.recordingFolderbtn.setText(QCoreApplication.translate("mainWindow", u"Open Recording Folder", None))
        self.ntripConnection.setText(QCoreApplication.translate("mainWindow", u"NTRIP Connection", None))
        self.saveButton.setText(QCoreApplication.translate("mainWindow", u"Save Data", None))
        self.btnGPSStatus.setText(QCoreApplication.translate("mainWindow", u"Open GPS Browser", None))
        self.prev_values.setText(QCoreApplication.translate("mainWindow", u"Prev", None))
        self.videoDepthai.setText(QCoreApplication.translate("mainWindow", u"Not Initialized", None))
        self.next_depthai.setText(QCoreApplication.translate("mainWindow", u"Next", None))
        self.Label_depthai.setText(QCoreApplication.translate("mainWindow", u"Depthai", None))
        self.serial_depthai.setTitle(QCoreApplication.translate("mainWindow", u"Video Connection", None))
        self.resolutionDepthai.setItemText(0, QCoreApplication.translate("mainWindow", u"720p", None))
        self.resolutionDepthai.setItemText(1, QCoreApplication.translate("mainWindow", u"1080p", None))
        self.resolutionDepthai.setItemText(2, QCoreApplication.translate("mainWindow", u"2K", None))
        self.resolutionDepthai.setItemText(3, QCoreApplication.translate("mainWindow", u"4K", None))

        self.startrecDepthai.setText(QCoreApplication.translate("mainWindow", u"Start Rec.", None))
        self.stoprecDepthai.setText(QCoreApplication.translate("mainWindow", u"Stop Rec.", None))
        self.fpsDepthaiLabel.setText(QCoreApplication.translate("mainWindow", u"FPS", None))
        self.fpsDepthai.setItemText(0, QCoreApplication.translate("mainWindow", u"5", None))
        self.fpsDepthai.setItemText(1, QCoreApplication.translate("mainWindow", u"10", None))
        self.fpsDepthai.setItemText(2, QCoreApplication.translate("mainWindow", u"15", None))
        self.fpsDepthai.setItemText(3, QCoreApplication.translate("mainWindow", u"20", None))
        self.fpsDepthai.setItemText(4, QCoreApplication.translate("mainWindow", u"25", None))
        self.fpsDepthai.setItemText(5, QCoreApplication.translate("mainWindow", u"30", None))
        self.fpsDepthai.setItemText(6, QCoreApplication.translate("mainWindow", u"35", None))
        self.fpsDepthai.setItemText(7, QCoreApplication.translate("mainWindow", u"40", None))
        self.fpsDepthai.setItemText(8, QCoreApplication.translate("mainWindow", u"45", None))
        self.fpsDepthai.setItemText(9, QCoreApplication.translate("mainWindow", u"50", None))
        self.fpsDepthai.setItemText(10, QCoreApplication.translate("mainWindow", u"55", None))
        self.fpsDepthai.setItemText(11, QCoreApplication.translate("mainWindow", u"60", None))

        self.resolutionDepthaiLabel.setText(QCoreApplication.translate("mainWindow", u"Resolution", None))
        self.initializeDepthai.setText(QCoreApplication.translate("mainWindow", u"Initialize Camera", None))
        self.exposureDepthaiLabel.setText(QCoreApplication.translate("mainWindow", u"Exposure", None))
        self.exposureDepthaiAdd.setText(QCoreApplication.translate("mainWindow", u"+", None))
        self.exposureDepthaiSub.setText(QCoreApplication.translate("mainWindow", u"-", None))
        self.ISODepthaiLabel.setText(QCoreApplication.translate("mainWindow", u"ISO", None))
        self.ISODepthaiAdd.setText(QCoreApplication.translate("mainWindow", u"+", None))
        self.ISODepthaiSub.setText(QCoreApplication.translate("mainWindow", u"-", None))
        self.focusDepthaiLabel.setText(QCoreApplication.translate("mainWindow", u"Focus", None))
        self.focusDepthaiAdd.setText(QCoreApplication.translate("mainWindow", u"+", None))
        self.focusDepthaiSub.setText(QCoreApplication.translate("mainWindow", u"-", None))
        self.brightnessDeptthaiLabel.setText(QCoreApplication.translate("mainWindow", u"Brightness", None))
        self.brightnessDepthaiAdd.setText(QCoreApplication.translate("mainWindow", u"+", None))
        self.brightnessDepthaiSub.setText(QCoreApplication.translate("mainWindow", u"-", None))
        self.contrastDepthaiSub.setText(QCoreApplication.translate("mainWindow", u"-", None))
        self.contrastDepthaiAdd.setText(QCoreApplication.translate("mainWindow", u"+", None))
        self.contrastDepthaiLabel.setText(QCoreApplication.translate("mainWindow", u"Contrast", None))
        self.saturationDepthaiSub.setText(QCoreApplication.translate("mainWindow", u"-", None))
        self.saturationDepthaiAdd.setText(QCoreApplication.translate("mainWindow", u"+", None))
        self.saturationDepthaiLabel.setText(QCoreApplication.translate("mainWindow", u"Saturation", None))
        self.sharpnessDepthaiLabel.setText(QCoreApplication.translate("mainWindow", u"Sharpness", None))
        self.sharpnessDepthaiAdd.setText(QCoreApplication.translate("mainWindow", u"+", None))
        self.sharpnessDepthaiSub.setText(QCoreApplication.translate("mainWindow", u"-", None))
        self.autoexposureDepthai.setText(QCoreApplication.translate("mainWindow", u"Autoexposure", None))
        self.autofocusDepthai.setText(QCoreApplication.translate("mainWindow", u"Autofocus", None))
        self.autowbDepthai.setText(QCoreApplication.translate("mainWindow", u"Auto White-balance", None))
        self.rosDepthaiUp.setText(QCoreApplication.translate("mainWindow", u"W", None))
        self.rosDepthaiLeft.setText(QCoreApplication.translate("mainWindow", u"A", None))
        self.rosDepthaiDown.setText(QCoreApplication.translate("mainWindow", u"S", None))
        self.rosDepthaiRight.setText(QCoreApplication.translate("mainWindow", u"D", None))
        self.prev_depthai.setText(QCoreApplication.translate("mainWindow", u"Prev", None))
        self.next_zed.setText(QCoreApplication.translate("mainWindow", u"Next", None))
        self.label_zed.setText(QCoreApplication.translate("mainWindow", u"ZED", None))
        self.serial_zed.setTitle(QCoreApplication.translate("mainWindow", u"Video Connection", None))
        self.resolutionZed.setItemText(0, QCoreApplication.translate("mainWindow", u"720p", None))
        self.resolutionZed.setItemText(1, QCoreApplication.translate("mainWindow", u"1080p", None))
        self.resolutionZed.setItemText(2, QCoreApplication.translate("mainWindow", u"2K", None))

        self.resolutionZed.setCurrentText(QCoreApplication.translate("mainWindow", u"1080p", None))
        self.startrecZed.setText(QCoreApplication.translate("mainWindow", u"Start Rec.", None))
        self.stoprecZed.setText(QCoreApplication.translate("mainWindow", u"Stop Rec.", None))
        self.fpsZedLabel.setText(QCoreApplication.translate("mainWindow", u"FPS", None))
        self.fpsZed.setItemText(0, QCoreApplication.translate("mainWindow", u"5", None))
        self.fpsZed.setItemText(1, QCoreApplication.translate("mainWindow", u"10", None))
        self.fpsZed.setItemText(2, QCoreApplication.translate("mainWindow", u"15", None))
        self.fpsZed.setItemText(3, QCoreApplication.translate("mainWindow", u"20", None))
        self.fpsZed.setItemText(4, QCoreApplication.translate("mainWindow", u"25", None))
        self.fpsZed.setItemText(5, QCoreApplication.translate("mainWindow", u"30", None))
        self.fpsZed.setItemText(6, QCoreApplication.translate("mainWindow", u"35", None))
        self.fpsZed.setItemText(7, QCoreApplication.translate("mainWindow", u"40", None))
        self.fpsZed.setItemText(8, QCoreApplication.translate("mainWindow", u"45", None))
        self.fpsZed.setItemText(9, QCoreApplication.translate("mainWindow", u"50", None))
        self.fpsZed.setItemText(10, QCoreApplication.translate("mainWindow", u"55", None))
        self.fpsZed.setItemText(11, QCoreApplication.translate("mainWindow", u"60", None))

        self.resolutionZedLabel.setText(QCoreApplication.translate("mainWindow", u"Resolution", None))
        self.initializeZed.setText(QCoreApplication.translate("mainWindow", u"Initialize Camera", None))
        self.exposureZedLabel.setText(QCoreApplication.translate("mainWindow", u"Exposure", None))
        self.exposureZedAdd.setText(QCoreApplication.translate("mainWindow", u"+", None))
        self.exposureZedSub.setText(QCoreApplication.translate("mainWindow", u"-", None))
        self.gainZedLabel.setText(QCoreApplication.translate("mainWindow", u"Gain", None))
        self.gainZedAdd.setText(QCoreApplication.translate("mainWindow", u"+", None))
        self.gainZedSub.setText(QCoreApplication.translate("mainWindow", u"-", None))
        self.hueZedLabel.setText(QCoreApplication.translate("mainWindow", u"Hue", None))
        self.hueZedAdd.setText(QCoreApplication.translate("mainWindow", u"+", None))
        self.hueZedSub.setText(QCoreApplication.translate("mainWindow", u"-", None))
        self.brightnessZedLabel.setText(QCoreApplication.translate("mainWindow", u"Brightness", None))
        self.brightnessZedAdd.setText(QCoreApplication.translate("mainWindow", u"+", None))
        self.brightnessZedSub.setText(QCoreApplication.translate("mainWindow", u"-", None))
        self.contrastZedSub.setText(QCoreApplication.translate("mainWindow", u"-", None))
        self.contrastZedAdd.setText(QCoreApplication.translate("mainWindow", u"+", None))
        self.contrastZedLabel.setText(QCoreApplication.translate("mainWindow", u"Contrast", None))
        self.saturationZedSub.setText(QCoreApplication.translate("mainWindow", u"-", None))
        self.saturationZedAdd.setText(QCoreApplication.translate("mainWindow", u"+", None))
        self.saturationZedLabel.setText(QCoreApplication.translate("mainWindow", u"Saturation", None))
        self.sharpnessZedLabel.setText(QCoreApplication.translate("mainWindow", u"Sharpness", None))
        self.sharpnessZedAdd.setText(QCoreApplication.translate("mainWindow", u"+", None))
        self.sharpnessZedSub.setText(QCoreApplication.translate("mainWindow", u"-", None))
        self.autoexposureZed.setText(QCoreApplication.translate("mainWindow", u"Autoexposure", None))
        self.rosZedUp.setText(QCoreApplication.translate("mainWindow", u"W", None))
        self.rosZedLeft.setText(QCoreApplication.translate("mainWindow", u"A", None))
        self.rosZedDown.setText(QCoreApplication.translate("mainWindow", u"S", None))
        self.rosZedRight.setText(QCoreApplication.translate("mainWindow", u"D", None))
        self.autobrightnessZed.setText(QCoreApplication.translate("mainWindow", u"Autobrightness", None))
        self.resetZed.setText(QCoreApplication.translate("mainWindow", u"Reset", None))
        self.videoZed.setText(QCoreApplication.translate("mainWindow", u"Not Initialized", None))
        self.prev_zed.setText(QCoreApplication.translate("mainWindow", u"Prev", None))
        self.menuFile.setTitle(QCoreApplication.translate("mainWindow", u"File", None))
        self.menuSettings.setTitle(QCoreApplication.translate("mainWindow", u"Settings", None))
        self.menuHelp.setTitle(QCoreApplication.translate("mainWindow", u"Help", None))
    # retranslateUi

