# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'ntrip_dialog.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractButton, QAbstractScrollArea, QApplication, QCheckBox,
    QComboBox, QDialog, QDialogButtonBox, QFrame,
    QLabel, QPlainTextEdit, QSizePolicy, QWidget)

class Ui_NtripDialog(object):
    def setupUi(self, NtripDialog):
        if not NtripDialog.objectName():
            NtripDialog.setObjectName(u"NtripDialog")
        NtripDialog.resize(332, 393)
        NtripDialog.setFocusPolicy(Qt.FocusPolicy.TabFocus)
        NtripDialog.setContextMenuPolicy(Qt.ContextMenuPolicy.DefaultContextMenu)
        NtripDialog.setWindowTitle(u"NTRIP Configuration")
        self.buttonBox = QDialogButtonBox(NtripDialog)
        self.buttonBox.setObjectName(u"buttonBox")
        self.buttonBox.setGeometry(QRect(10, 350, 311, 41))
        self.buttonBox.setOrientation(Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QDialogButtonBox.StandardButton.Cancel|QDialogButtonBox.StandardButton.Ok)
        self.labelServer = QLabel(NtripDialog)
        self.labelServer.setObjectName(u"labelServer")
        self.labelServer.setGeometry(QRect(10, 12, 67, 17))
        self.labelPort = QLabel(NtripDialog)
        self.labelPort.setObjectName(u"labelPort")
        self.labelPort.setGeometry(QRect(10, 43, 67, 17))
        self.line = QFrame(NtripDialog)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(10, 90, 311, 16))
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.labelUser = QLabel(NtripDialog)
        self.labelUser.setObjectName(u"labelUser")
        self.labelUser.setGeometry(QRect(11, 114, 67, 17))
        self.labelPassword = QLabel(NtripDialog)
        self.labelPassword.setObjectName(u"labelPassword")
        self.labelPassword.setGeometry(QRect(11, 142, 67, 17))
        self.labelDatatype = QLabel(NtripDialog)
        self.labelDatatype.setObjectName(u"labelDatatype")
        self.labelDatatype.setGeometry(QRect(10, 184, 81, 17))
        self.labelVersion = QLabel(NtripDialog)
        self.labelVersion.setObjectName(u"labelVersion")
        self.labelVersion.setGeometry(QRect(10, 214, 81, 17))
        self.labelSourcetable = QLabel(NtripDialog)
        self.labelSourcetable.setObjectName(u"labelSourcetable")
        self.labelSourcetable.setGeometry(QRect(10, 275, 91, 17))
        self.line_2 = QFrame(NtripDialog)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(10, 250, 311, 20))
        self.line_2.setFrameShape(QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.labelGGA = QLabel(NtripDialog)
        self.labelGGA.setObjectName(u"labelGGA")
        self.labelGGA.setGeometry(QRect(10, 307, 91, 17))
        self.server = QPlainTextEdit(NtripDialog)
        self.server.setObjectName(u"server")
        self.server.setGeometry(QRect(100, 10, 211, 22))
        self.server.setMinimumSize(QSize(0, 22))
        self.server.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.server.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.server.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.port = QPlainTextEdit(NtripDialog)
        self.port.setObjectName(u"port")
        self.port.setGeometry(QRect(100, 40, 111, 22))
        self.port.setMinimumSize(QSize(0, 22))
        self.port.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.port.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.port.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.https = QCheckBox(NtripDialog)
        self.https.setObjectName(u"https")
        self.https.setGeometry(QRect(100, 70, 92, 23))
        self.https.setChecked(False)
        self.user = QPlainTextEdit(NtripDialog)
        self.user.setObjectName(u"user")
        self.user.setGeometry(QRect(100, 110, 211, 22))
        self.user.setMinimumSize(QSize(0, 22))
        self.user.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.user.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.user.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.password = QPlainTextEdit(NtripDialog)
        self.password.setObjectName(u"password")
        self.password.setGeometry(QRect(100, 140, 211, 22))
        self.password.setMinimumSize(QSize(0, 22))
        self.password.setInputMethodHints(Qt.InputMethodHint.ImhSensitiveData)
        self.password.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.password.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.password.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.password.setPlainText(u"")
        self.sourcetable = QComboBox(NtripDialog)
        self.sourcetable.setObjectName(u"sourcetable")
        self.sourcetable.setGeometry(QRect(120, 270, 191, 25))
        self.ggainterval = QPlainTextEdit(NtripDialog)
        self.ggainterval.setObjectName(u"ggainterval")
        self.ggainterval.setGeometry(QRect(124, 305, 81, 22))
        self.ggainterval.setMinimumSize(QSize(0, 22))
        self.ggainterval.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.ggainterval.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.ggainterval.setSizeAdjustPolicy(QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.version = QComboBox(NtripDialog)
        self.version.addItem("")
        self.version.addItem("")
        self.version.setObjectName(u"version")
        self.version.setEnabled(True)
        self.version.setGeometry(QRect(100, 210, 101, 25))
        self.version.setEditable(False)
        self.datatype = QComboBox(NtripDialog)
        self.datatype.addItem("")
        self.datatype.addItem("")
        self.datatype.setObjectName(u"datatype")
        self.datatype.setEnabled(True)
        self.datatype.setGeometry(QRect(100, 180, 101, 25))
        self.datatype.setEditable(False)

        self.retranslateUi(NtripDialog)
        self.buttonBox.accepted.connect(NtripDialog.accept)
        self.buttonBox.rejected.connect(NtripDialog.reject)

        self.version.setCurrentIndex(1)
        self.datatype.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(NtripDialog)
    # setupUi

    def retranslateUi(self, NtripDialog):
#if QT_CONFIG(statustip)
        NtripDialog.setStatusTip("")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        NtripDialog.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(accessibility)
        NtripDialog.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.labelServer.setText(QCoreApplication.translate("NtripDialog", u"Server", None))
        self.labelPort.setText(QCoreApplication.translate("NtripDialog", u"Port", None))
        self.labelUser.setText(QCoreApplication.translate("NtripDialog", u"User", None))
        self.labelPassword.setText(QCoreApplication.translate("NtripDialog", u"Password", None))
        self.labelDatatype.setText(QCoreApplication.translate("NtripDialog", u"Data Type", None))
        self.labelVersion.setText(QCoreApplication.translate("NtripDialog", u"Version", None))
        self.labelSourcetable.setText(QCoreApplication.translate("NtripDialog", u"Sourcetable", None))
        self.labelGGA.setText(QCoreApplication.translate("NtripDialog", u"GGA Interval", None))
        self.server.setPlainText("")
        self.port.setPlainText("")
        self.https.setText(QCoreApplication.translate("NtripDialog", u"HTTPS", None))
        self.user.setPlainText("")
#if QT_CONFIG(whatsthis)
        self.password.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
        self.ggainterval.setPlainText("")
        self.version.setItemText(0, QCoreApplication.translate("NtripDialog", u"1.0", None))
        self.version.setItemText(1, QCoreApplication.translate("NtripDialog", u"2.0", None))

        self.datatype.setItemText(0, QCoreApplication.translate("NtripDialog", u"RTCM", None))
        self.datatype.setItemText(1, QCoreApplication.translate("NtripDialog", u"SPARTN", None))

    # retranslateUi

